name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Check code style
      run: mvn verify -DsyntaxChecker.isFailOnWarning=true -DsyntaxFormatter.skip=true
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build documentation with Maven
      run: mvn javadoc:javadoc

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
          name: artifact
          path: target/io-project-architecture-*.jar
    
    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
          name: documentation
          path: target/site/
    
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
